from sqlalchemy import Column, Integer, SmallInteger, Float, DateTime, TIMESTAMP, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property

Base = declarative_base()

class MatchTeamLatestSummaryOld(Base):
    __tablename__ = 'match_team_latest_summary_old'

    id = Column(Integer, primary_key=True, autoincrement=True)
    curr_match_id = Column('curr_match_id', Integer, comment='当前比赛id')
    curr_match_start_time = Column('curr_match_start_time', DateTime, comment='当前比赛时间(由onlie补充的不一定准确)')
    curr_league_id = Column('curr_league_id', Integer, comment='联赛ID')
    is_curr_match_league = Column('is_curr_match_league', SmallInteger, comment='当前比赛是否是联赛（否为杯赛）')
    team_id = Column('team_id', Integer, comment='当前比赛以哪个球队为维度，默认以主队为维度')
    other_team_id = Column('other_team_id', Integer, comment='对方的teamId')
    recent_days = Column('recentDays', SmallInteger, comment='最近多少天')

    # My recent 1 data (我方最近第一场比赛数据)
    my_recent1_start_pk = Column('myRecent1StartPk', Float, comment='最近第一场的盘口（相对于自己）')
    my_recent1_start_time = Column('myRecent1StartTime', DateTime, comment='最近第一场比赛的时间')
    my_recent1_result = Column('myRecent1Result', SmallInteger)
    my_recent1_goals = Column('myRecent1Goals', SmallInteger)
    my_recent1_loose_goals = Column('myRecent1LooseGoals', SmallInteger)
    my_recent1_is_tech = Column('myRecent1IsTech', SmallInteger)
    my_recent1_tech_level = Column('myRecent1TechLevel', SmallInteger)
    my_recent1_is_league = Column('myRecent1IsLeague', SmallInteger)
    my_recent1_short_all = Column('myRecent1ShortAll', SmallInteger)
    my_recent1_mult_short_all = Column('myRecent1MultShortAll', Float)
    my_recent1_mult_short_jiao_all = Column('myRecent1MultShortJiaoAll', Float)
    my_recent1_mult_ser_attack = Column('myRecent1MultSerAttack', Float)
    my_recent1_mult_attack_all = Column('myRecent1MultAttackAll', Float)

    # My recent 2 data (我方最近第二场比赛数据)
    my_recent2_start_pk = Column('myRecent2StartPk', Float, comment='最近第二场的盘口（相对于自己）')
    my_recent2_start_time = Column('myRecent2StartTime', DateTime, comment='最近第二场比赛的时间')
    my_recent2_result = Column('myRecent2Result', SmallInteger)
    my_recent2_goals = Column('myRecent2Goals', SmallInteger)
    my_recent2_loose_goals = Column('myRecent2LooseGoals', SmallInteger)
    my_recent2_is_tech = Column('myRecent2IsTech', SmallInteger)
    my_recent2_tech_level = Column('myRecent2TechLevel', SmallInteger)
    my_recent2_is_league = Column('myRecent2IsLeague', SmallInteger)
    my_recent2_short_all = Column('myRecent2ShortAll', SmallInteger)
    my_recent2_mult_short_all = Column('myRecent2MultShortAll', Float)
    my_recent2_mult_short_jiao_all = Column('myRecent2MultShortJiaoAll', Float)
    my_recent2_mult_ser_attack = Column('myRecent2MultSerAttack', Float)
    my_recent2_mult_attack_all = Column('myRecent2MultAttackAll', Float)

    # My statistics (我方统计数据)
    my_recent_count = Column('myRecentCount', SmallInteger, comment='我方球队在最近多少天有多少比赛数量')
    my_avg_goals = Column('myAvgGoals', Float, comment='场均进球数量')
    my_avg_loose_goals = Column('myAvgLooseGoals', Float, comment='场均失球数量')
    my_goals0_count = Column('myGoals0Count', SmallInteger, comment='进球为0的比赛数量')
    my_goals1_count = Column('myGoals1Count', SmallInteger, comment='进球小于=1的数量')
    my_goals2_count = Column('myGoals2Count', SmallInteger, comment='进球大于等于2的数量')
    my_goals3_count = Column('myGoals3Count', SmallInteger, comment='进球大于等于3的数量')
    my_loose_goals0_count = Column('myLooseGoals0Count', SmallInteger, comment='失球为0的数量')
    my_loose_goals1_count = Column('myLooseGoals1Count', SmallInteger, comment='失球小于等于1的数量')
    my_loose_goals2_count = Column('myLooseGoals2Count', SmallInteger, comment='失球大于等于2的数量')
    my_loose_goals3_count = Column('myLooseGoals3Count', SmallInteger, comment='失球大于等于3的数量')
    my_win_count = Column('myWinCount', SmallInteger, comment='赢球数量')
    my_loose_count = Column('myLooseCount', SmallInteger, comment='输球数量')
    my_rq_count = Column('myRqCount', SmallInteger, comment='让球盘数量')
    my_bei_rq_count = Column('myBeiRqCount', SmallInteger, comment='受让球盘数量')
    my_tech_effect_count = Column('myTechEffectCount', SmallInteger, comment='所有技术统计有效的比赛数量')
    my_tech_advan1_count = Column('myTechAdvan1Count', SmallInteger, comment='技术统计领先优势1')
    my_tech_advan2_count = Column('myTechAdvan2Count', SmallInteger, comment='技术统计领先优势2')
    my_tech_advan3_count = Column('myTechAdvan3Count', SmallInteger)
    my_tech_advan4_count = Column('myTechAdvan4Count', SmallInteger)
    my_tech_loose_advan1_count = Column('myTechLooseAdvan1Count', SmallInteger, comment='技术统计落后1')
    my_tech_loose_advan2_count = Column('myTechLooseAdvan2Count', SmallInteger, comment='技术统计落后2')
    my_tech_loose_advan3_count = Column('myTechLooseAdvan3Count', SmallInteger)
    my_tech_loose_advan4_count = Column('myTechLooseAdvan4Count', SmallInteger)
    my_tech_bad_tech_count = Column('myTechBadTechCount', SmallInteger, comment='技术统计很糟糕的（盘口小于1,射门总数小于4或者（射正为0，射偏=4）或者射门小于对面的3.8倍，危险进攻-1.5，角球小于对方的且小于5）')
    my_tech_avg_short_all = Column('myTechAvgShortAll', Float, comment='平均每场射门数（进攻评定）')
    my_tech_avg_short_ok = Column('myTechAvgShortOk', Float, comment='平均射正数（进攻评定）')
    my_tech_avg_short_jiao_all = Column('myTechAvgShortJiaoAll', Float, comment='平均角球+射门总数（进攻评定）')
    my_tech_short_less4_count = Column('myTechShortLess4Count', SmallInteger, comment='射门数小于4的场次，不包括4（进攻评定）')
    my_tech_short_less5_count = Column('myTechShortLess5Count', SmallInteger, comment='射门数小于5的场次，不包括5（进攻评定）')
    my_tech_short_less6_count = Column('myTechShortLess6Count', SmallInteger, comment='射门数小于6的场次，不包括6（进攻评定）')
    my_tech_short_avg_score = Column('myTechShortAvgScore', Float, comment='射门总数/进球数总数（进攻评定）')
    my_tech_avg_bei_short_all = Column('myTechAvgBeiShortAll', Float, comment='平均每场对方射门数（防守评定）')
    my_tech_avg_bei_short_ok = Column('myTechAvgBeiShortOk', Float, comment='平均对方射正数（（防守评定）')
    my_tech_avg_bei_short_jiao_all = Column('myTechAvgBeiShortJiaoAll', Float, comment='平均对方角球+射门总数（（防守评定）')
    my_tech_bei_short_avg_score = Column('myTechBeiShortAvgScore', Float, comment='对方射门总数/进球数总数（防守评定）')
    my_tech_bei_short_less4_count = Column('myTechBeiShortLess4Count', SmallInteger, comment='射门数小于4的场次，不包括5（防守评定）')
    my_tech_bei_short_less5_count = Column('myTechBeiShortLess5Count', SmallInteger, comment='射门数小于5的场次，不包括5（防守评定）')
    my_tech_bei_short_less6_count = Column('myTechBeiShortLess6Count', SmallInteger, comment='射门数小于6的场次，不包括5（防守评定）')
    my_match_league_count = Column('myMatchLeagueCount', SmallInteger, comment='联赛数量')
    my_league_avg_goals = Column('myLeagueAvgGoals', Float, comment='球队场均进球数量（联赛）')
    my_league_avg_loose_goals = Column('myLeagueAvgLooseGoals', Float, comment='球队场均失球数量（联赛）')
    my_league_win_count = Column('myLeagueWinCount', SmallInteger, comment='球队赢球场次（联赛）')
    my_league_loose_count = Column('myLeagueLooseCount', SmallInteger, comment='球队输球场次')
    my_league_rq_count = Column('myLeagueRqCount', SmallInteger, comment='球队让球数量（联赛）')
    my_league_bei_rq_count = Column('myLeagueBeiRqCount', SmallInteger, comment='球队受让球数量（联赛）')

    # Loose team recent data (对方最近比赛数据)
    loose_recent1_start_pk = Column('looseRecent1StartPk', Float)
    loose_recent1_start_time = Column('looseRecent1StartTime', DateTime)
    loose_recent1_result = Column('looseRecent1Result', SmallInteger)
    loose_recent1_goals = Column('looseRecent1Goals', SmallInteger)
    loose_recent1_loose_goals = Column('looseRecent1LooseGoals', SmallInteger)
    loose_recent1_is_tech = Column('looseRecent1IsTech', SmallInteger)
    loose_recent1_tech_level = Column('looseRecent1TechLevel', SmallInteger)
    loose_recent1_is_league = Column('looseRecent1IsLeague', SmallInteger)
    loose_recent1_short_all = Column('looseRecent1ShortAll', SmallInteger)
    loose_recent1_mult_short_all = Column('looseRecent1MultShortAll', Float)
    loose_recent1_mult_short_jiao_all = Column('looseRecent1MultShortJiaoAll', Float)
    loose_recent1_mult_ser_attack = Column('looseRecent1MultSerAttack', Float)
    loose_recent1_mult_attack_all = Column('looseRecent1MultAttackAll', Float)

    loose_recent2_start_pk = Column('looseRecent2StartPk', Float)
    loose_recent2_start_time = Column('looseRecent2StartTime', DateTime)
    loose_recent2_result = Column('looseRecent2Result', SmallInteger)
    loose_recent2_goals = Column('looseRecent2Goals', SmallInteger)
    loose_recent2_loose_goals = Column('looseRecent2LooseGoals', SmallInteger)
    loose_recent2_is_tech = Column('looseRecent2IsTech', SmallInteger)
    loose_recent2_tech_level = Column('looseRecent2TechLevel', SmallInteger)
    loose_recent2_is_league = Column('looseRecent2IsLeague', SmallInteger)
    loose_recent2_short_all = Column('looseRecent2ShortAll', SmallInteger)
    loose_recent2_mult_short_all = Column('looseRecent2MultShortAll', Float)
    loose_recent2_mult_short_jiao_all = Column('looseRecent2MultShortJiaoAll', Float)
    loose_recent2_mult_ser_attack = Column('looseRecent2MultSerAttack', Float)
    loose_recent2_mult_attack_all = Column('looseRecent2MultAttackAll', Float)

    # Loose team statistics (对方统计数据)
    loose_recent_count = Column('looseRecentCount', SmallInteger)
    loose_avg_goals = Column('looseAvgGoals', Float)
    loose_avg_loose_goals = Column('looseAvgLooseGoals', Float)
    loose_goals0_count = Column('looseGoals0Count', SmallInteger)
    loose_goals1_count = Column('looseGoals1Count', SmallInteger)
    loose_goals2_count = Column('looseGoals2Count', SmallInteger)
    loose_goals3_count = Column('looseGoals3Count', SmallInteger)
    loose_loose_goals0_count = Column('looseLooseGoals0Count', SmallInteger)
    loose_loose_goals1_count = Column('looseLooseGoals1Count', SmallInteger)
    loose_loose_goals2_count = Column('looseLooseGoals2Count', SmallInteger)
    loose_loose_goals3_count = Column('looseLooseGoals3Count', SmallInteger)
    loose_win_count = Column('looseWinCount', SmallInteger)
    loose_loose_count = Column('looseLooseCount', SmallInteger)
    loose_rq_count = Column('looseRqCount', SmallInteger)
    loose_bei_rq_count = Column('looseBeiRqCount', SmallInteger)
    loose_tech_avg_short_all = Column('looseTechAvgShortAll', Float)
    loose_tech_avg_short_ok = Column('looseTechAvgShortOk', Float)
    loose_tech_avg_short_jiao_all = Column('looseTechAvgShortJiaoAll', Float)
    loose_tech_short_less4_count = Column('looseTechShortLess4Count', SmallInteger)
    loose_tech_short_less5_count = Column('looseTechShortLess5Count', SmallInteger)
    loose_tech_short_less6_count = Column('looseTechShortLess6Count', SmallInteger)
    loose_tech_short_avg_score = Column('looseTechShortAvgScore', Float)
    loose_tech_avg_bei_short_all = Column('looseTechAvgBeiShortAll', Float)
    loose_tech_avg_bei_short_ok = Column('looseTechAvgBeiShortOk', Float)
    loose_tech_avg_bei_short_jiao_all = Column('looseTechAvgBeiShortJiaoAll', Float)
    loose_tech_bei_short_avg_score = Column('looseTechBeiShortAvgScore', Float)
    loose_tech_bei_short_less4_count = Column('looseTechBeiShortLess4Count', SmallInteger)
    loose_tech_bei_short_less5_count = Column('looseTechBeiShortLess5Count', SmallInteger)
    loose_tech_bei_short_less6_count = Column('looseTechBeiShortLess6Count', SmallInteger)
    loose_tech_effect_count = Column('looseTechEffectCount', SmallInteger)
    loose_tech_advan1_count = Column('looseTechAdvan1Count', SmallInteger)
    loose_tech_advan2_count = Column('looseTechAdvan2Count', SmallInteger)
    loose_tech_advan3_count = Column('looseTechAdvan3Count', SmallInteger)
    loose_tech_advan4_count = Column('looseTechAdvan4Count', SmallInteger)
    loose_tech_loose_advan1_count = Column('looseTechLooseAdvan1Count', SmallInteger)
    loose_tech_loose_advan2_count = Column('looseTechLooseAdvan2Count', SmallInteger)
    loose_tech_loose_advan3_count = Column('looseTechLooseAdvan3Count', SmallInteger)
    loose_tech_loose_advan4_count = Column('looseTechLooseAdvan4Count', SmallInteger)
    loose_tech_bad_tech_count = Column('looseTechBadTechCount', SmallInteger)
    loose_match_league_count = Column('looseMatchLeagueCount', SmallInteger)
    loose_league_avg_goals = Column('looseLeagueAvgGoals', Float)
    loose_league_avg_loose_goals = Column('looseLeagueAvgLooseGoals', Float)
    loose_league_win_count = Column('looseLeagueWinCount', SmallInteger)
    loose_league_loose_count = Column('looseLeagueLooseCount', SmallInteger)
    loose_league_rq_count = Column('looseLeagueRqCount', SmallInteger)
    loose_league_bei_rq_count = Column('looseLeagueBeiRqCount', SmallInteger)

    create_time = Column('create_time', TIMESTAMP, default=text("CURRENT_TIMESTAMP"))
